import React, { useState } from "react";
import {
  AppBar,
  Toolbar,
  Button,
  Tabs,
  Tab,
  SwipeableDrawer,
} from "@mui/material";
import { ShoppingBagOutlined, ShoppingCart } from "@mui/icons-material";
import { Box } from "@mui/system";

import { useRouter } from "next/router";

import style from "./header.module.css";
import Head from "next/head";
import Cart from "../cart/Cart";
import { useStateContext } from "@/context/StateContext";

const NavBar = () => {
  const router = useRouter();
  const [value, setValue] = useState(0);
  const [cartOpen, setCartOpen] = useState(false);
  const { totalQuantities } = useStateContext();

  const mapTabs = ["products", "about", "contact"];

  const changeTabHandler = (e: React.SyntheticEvent, value: number) => {
    setValue(value);
    router.push(`/${mapTabs[value]}`);
  };

  const list = () => (
    <Box
      sx={{ width: "500px" }}
      role='presentation'
      onKeyDown={toggleDrawer(false)}
      alignItems={"center"}
      ml={10}
    >
      <Cart />
    </Box>
  );

  const toggleDrawer =
    (open: boolean) => (event: React.KeyboardEvent | React.MouseEvent) => {
      if (
        event &&
        event.type === "keydown" &&
        ((event as React.KeyboardEvent).key === "Tab" ||
          (event as React.KeyboardEvent).key === "Shift")
      ) {
        return;
      }

      setCartOpen(open);
    };

  return (
    <>
      <Head>
        <title>DVT Online Shop</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <AppBar color='secondary'>
        <Toolbar>
          <ShoppingCart />
          <Tabs
            value={value}
            onChange={changeTabHandler}
            aria-label='basic tabs example'
            indicatorColor='secondary'
            textColor='inherit'
          >
            <Tab label='Products' />
            <Tab label='About Us' />
            <Tab label='Contact Us' />
          </Tabs>

          <>
            <Button
              className={style.button}
              onClick={toggleDrawer(true)}
            >
              <ShoppingBagOutlined color='action' />
              <span className={style.circle}>{totalQuantities}</span>
            </Button>
            <SwipeableDrawer
              anchor={"right"}
              open={cartOpen}
              onClose={toggleDrawer(false)}
              onOpen={toggleDrawer(true)}
            >
              {list()}
            </SwipeableDrawer>
          </>
        </Toolbar>
      </AppBar>
    </>
  );
};

export default NavBar;
