import React from "react";
import Header from "../header/NavBar";
import Footer from "../footer/Footer";
import Head from "next/head";
import style from "./layout.module.css";

interface Props {
  children?: React.ReactNode;
}
const Layout = (props: Props) => {
  return (
    <>
      <div className={style.main}>
        <Head>
          <title>DVT Online Shop</title>
          <meta
            name='description'
            content='Generated by create next app'
          />
          <meta
            name='viewport'
            content='width=device-width, initial-scale=1'
          />
          <link
            rel='icon'
            href='/favicon.ico'
          />
        </Head>
        <header>
          <Header />
        </header>
        <main>{props.children}</main>
      </div>
      <footer>
        <Footer />
      </footer>
    </>
  );
};

export default Layout;
